# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Healthy Urban Mobility"
title_pt: "Mobilidade Urbana Saudável"
email: "info@hum-mus.org"
description: >- # this means to ignore newlines until "baseurl:"
 The Healthy Urban Mobility (HUM) project is a study to understand the impact of everyday (im)mobility on health and wellbeing with a variety of social groups living in different neighbourhoods in Brazil and the UK, and also to explore the potential for participatory mobilities planning with local communities to support and develop solutions for healthy urban mobility
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hum-mus.org" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
